#SPDX-License-Identifier: MIT-0
---
# tasks file for httpd
- name: Install Apache
  ansible.builtin.apt:
    name: apache2
    state: present
- name: Create index.html
  copy:
    dest: /var/www/html/index.html
    content: "<h1>Hello from Ansible!</h1>"
    owner: root
    group: root
    mode: '0644'
